### ISSUE TITLE
Akka version mismatch reported on stackoverflow

### ISSUE THREAD

**Issue by leviramsey** [akka/akka-distributed-workers-scala.g8#17]
See https://stackoverflow.com/questions/58956131/how-to-fix-all-the-errors-and-successfully-run-the-akka-distributed-workers-samp

It appears that post akka-2.6 release, even on the default akka-2.5 branch, this project pulls in a blend of mostly 2.6 dependencies along with persistence-query 2.5.23.

**Comment by raboof** [comment]
That's embarassing! Looks like we didn't have travis cron jobs set up for this project, I've added those just now.

**Comment by chbatey** [comment]
:+1: for the cron

**Comment by leviramsey** [comment]
I was just about to post that when I installed g8 and tried to reproduce, everything was coming up 2.5.

Seems to be fixed now.
